# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved. SPDX-License-Identifier: MIT-0
baseURL = "https://rddefauw.gitlab.io/fargate_workshop"
canonifyURLs = true
languageCode = "en-us"
title = "ECS Fargate Workshop"

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

[params]
# Change default color scheme with a variant one. Can be "red", "blue", "green".
themeVariant = "mine"


# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

