version: 0.2

phases:
    pre_build:
        commands:
        - echo Pulling the hadolint docker image
        - docker pull hadolint/hadolint:v1.16.2
    build:
        commands:
        - echo Build started on `date`
        - cd $CODEBUILD_SRC_DIR
        - echo Scanning with Hadolint...
        - result=`docker run --rm -i hadolint/hadolint:v1.16.2 hadolint -f json - < Dockerfile`
    post_build:
        commands:
        - echo $result
        - echo Build completed on `date`